Updated to include all new changes from recent cprint changes. Added comments to make it more clear which parts are from which fuctions in the cprint script. Added to local to common-named variables to avoid any issues.

diff --git a/cprint_full_function b/cprint_full_function
--- a/cprint_full_function
+++ b/cprint_full_function
@@ -30,7 +30,7 @@ print()
 		On_Cyan='\033[46m'        # Cyan
 		On_White='\033[47m'       # White
 		NC='\033[m'               # Color Reset
-	else 
+	else
 		Black='\e[0;30m'        # Black
 		Red='\e[0;31m'          # Red
 		Green='\e[0;32m'        # Green
@@ -60,34 +60,34 @@ print()
 		NC="\e[m"               # Color Reset
 	fi
 	if which cowsay >&/dev/null; then
-		CS="$(which cowsay)"
+		local CS="$(which cowsay)"
 	else
-		CS=""
+		local CS=""
 	fi
 	if which figlet >&/dev/null; then
-		FIG="$(which figlet)"
+		local FIG="$(which figlet)"
 	else
-		FIG=""
+		local FIG=""
 	fi
-	if which printf >&/dev/null; then	
-		PRINTF_E=0
+	if which printf >&/dev/null; then
+		local PRINTF_E=0
 	else
-		PRINTF_E=1
+		local PRINTF_E=1
 	fi
-	colors=( "$Red" "$Green" "$Gellow" "$Blue" "$Purple" "$Cyan" )
-	DEBUG=0
-	FGND=""
-	BKGN=""
-	BOLD=0
-	NL=1
-	PNL=0
-	STRING=" "
-	STYLE=""
-	POS=0
-	RAINBOW=0
-	while getopts "f:b:IcnpFAKRGYBPCWDS:" opt
+	local DEBUG=0
+	local FGND=""
+	local BKGN=""
+	local BOLD=0
+	local NL=1
+	local PNL=0
+	local STRING=" "
+	local STYLE=""
+	local POS=0
+	local RAINBOW=0
+	local ERR_OUT=0
+	while getopts "f:b:IcnpFAKRGYBPCWDS:" cprint_opt
 	do
-		case "$opt" in
+		case "$cprint_opt" in
 			"f")					# Set foreground/text color.
 				case "$OPTARG" in
 					"black") [ $BOLD -eq 0 ] && FGND="$Black" || FGDN="$BBlack" ;;
@@ -98,7 +98,7 @@ print()
 					"purple") [ $BOLD -eq 0 ] && FGND="$Purple" || FGND="$BPurple" ;;
 					"cyan") [ $BOLD -eq 0 ] && FGND="$Cyan" || FGND="$BCyan" ;;
 					"white") [ $BOLD -eq 0 ] && FGND="$White" || FGND="$BWhite" ;;
-					"*") [ $DEBUG -eq 1 ] && echo "Unrecognized Arguement: $OPTARG" ;;
+					"*") [ $DEBUG -eq 1 ] && (>&2 echo "Unrecognized Arguement: $OPTARG") ;;
 				esac
 				;;
 			"b")					# Set background color.
@@ -111,11 +111,13 @@ print()
 					"purple") BKGN="$On_Purple" ;;
 					"cyan") BKGN="$On_Cyan" ;;
 					"white") BKGN="$On_White" ;;
-					"*") [ $DEBUG -eq 1 ] && echo "Unrecognized Arguement: $OPTARG" ;;
+					"*") [ $DEBUG -eq 1 ] && (>&2 echo "Unrecognized Arguement: $OPTARG") ;;
 				esac
 				;;
 			"I") BOLD=1 ;;				# Enable bold text.
 			"c")
+				local WIDTH=0
+				local POS=0
 				WIDTH=$(tput cols)					# Current screen width
 				if [ $WIDTH -le 80 ]; then
 					POS=0
@@ -137,66 +139,112 @@ print()
 			"W") [ $BOLD -eq 0 ] && FGND="$White" || FGND="$BWhite";;
 			"D") DEBUG=1 ;;
 			"S") STRING="$OPTARG" ;;
-			"*") [ $DEBUG -eq 1 ] && echo "Unknown Arguement: $opt" ;;
+			"*") [ $DEBUG -eq 1 ] && (>&2 echo "Unknown Arguement: $opt") ;;
 		esac
 	done
 	if [[ "$STRING" == " " ]];then
 		shift "$((OPTIND - 1))"
-		STRING="$@" 
+		STRING="$@"
 	fi
 	if [ $DEBUG -eq 1 ]; then
-		echo "FGND: $FGND"
-		echo "BKGN: $BKGN"
-		echo "BOLD: $BOLD"
-		echo "NL: $NL"
-		echo "PNL: $PNL"
-		echo "POS: $POS"
-		echo "STYLE: $STYLE"
-		echo "STRING: $STRING"
+		(>&2 echo "FGND: $FGND")
+		(>&2 echo "BKGN: $BKGN")
+		(>&2 echo "BOLD: $BOLD")
+		(>&2 echo "NL: $NL")
+		(>&2 echo "PNL: $PNL")
+		(>&2 echo "POS: $POS")
+		(>&2 echo "STYLE: $STYLE")
+		(>&2 echo "RAINBOW: $RAINBOW")
+		(>&2 echo "PRINTF_E: $PRINTF_E")
+		(>&2 echo "ERR_OUT: $ERR_OUT")
+		(>&2 echo "STRING: $STRING")
 	fi
-	while [ $PNL -ne 0 ] 
+	#process_prenl()
+	while [ $PNL -ne 0 ]
 	do
 		if [ $PRINTF_E -eq 0 ];then
-			printf "\n"
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 printf "\n")
+			else
+				printf "\n"
+			fi
 		else
-			echo ""
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 echo "")
+			else
+				echo ""
+			fi
 		fi
 		((PNL--))
 	done
-	[ ! -z $STYLE ] && STRING="$($STYLE $STRING)"
+	#process_string()
+	string_proc="$STRING"
+	[ ! -z $STYLE ] && string_proc="$($STYLE $string_proc)"
 	if [ $POS -eq 0 ]; then
-		[ ! -z $BKGN ] && STRING="$BKGN$STRING"
+		[ ! -z $BKGN ] && string_proc="$BKGN$string_proc"
 		if [ $RAINBOW -eq 1 ]; then
-			STRING_r=""
-			words=($STRING)
+			string_proc_r=""
+			words=($string_proc)
 			for c in "${words[@]}"
 			do
-				random_color
-				STRING_r="$STRING_r$FGND$c "
+				#random_color()
+				colors=( "$Red" "$Green" "$Gellow" "$Blue" "$Purple" "$Cyan" )
+				FGND="${colors[$RANDOM % ${#colors[@]}]}"
+				[ $DEBUG -eq 1 ] && (>&2 echo "Random seed: $RANDOM")
+				string_proc_r="$string_proc_r$FGND$c "
 			done
-			STRING=$STRING_r
+			string_proc=$string_proc_r
 		else
-			[ ! -z $FGND ] && STRING="$FGND$STRING"
+			[ ! -z $FGND ] && string_proc="$FGND$string_proc"
 		fi
-		[ ! -z $FGND ] || [ ! -z $BKGN ] && STRING="$STRING$NC"	# Append color reset if foreground/background is set.
+		[ ! -z $FGND ] || [ ! -z $BKGN ] && string_proc="$string_proc$NC"	# Append color reset if foreground/background is set.
 		if [ $PRINTF_E -eq 0 ]; then
-			printf -- "$string_proc"
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 printf -- "$string_proc")
+			else
+				printf -- "$string_proc"
+			fi
 		else
-			[ $DEBUG -eq 1 ] && echo "printf not found, reverting to echo."
-			echo "$string_proc"
+			[ $DEBUG -eq 1 ] && (>&2 echo "printf not found, reverting to echo.")
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 echo "$string_proc")
+			else
+				echo "$string_proc"
+			fi
 		fi
 	else
 		if [ $PRINTF_E -eq 0 ]; then
-			printf -- "$FGND$BKGN%$POS"s"$NC" "$string_proc"
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 printf -- "$FGND$BKGN%$POS"s"$NC" "$string_proc")
+			else
+				printf -- "$FGND$BKGN%$POS"s"$NC" "$string_proc"
+			fi
 		else
-			[ $DEBUG -eq 1 ] && echo "printf not found, reverting to echo."
-			echo "$FGND""$BKGN""$string_proc""$NC"
+			[ $DEBUG -eq 1 ] && (>&2 "printf not found, reverting to echo.")
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 echo "$FGND""$BKGN""$string_proc""$NC")
+			else
+				echo "$FGND""$BKGN""$string_proc""$NC"
+			fi
 		fi
 	fi
+	#process_nl()
 	if [ $PRINTF_E -eq 0 ];then
-		[ $NL -eq 1 ] && printf "\n"
+		if [ $NL -eq 1 ]; then
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 printf "\n")
+			else
+				printf "\n"
+			fi
+		fi
 	else
-		[ $NL -eq 1 ] && echo ""
+		if [ $NL -eq 1 ]; then
+			if [ $ERR_OUT -eq 1 ]; then
+				(>&2 echo "")
+			else
+				echo ""
+			fi
+		fi
 	fi
 }
 tests()
@@ -209,16 +257,16 @@ tests()
 	print -c $V "Centered"
 	print -F $V "Figlet"
 	print -A $V "Cowsay"
-	print -K $V "Black" 
-	print -R $V "Red" 
+	print -K $V "Black"
+	print -R $V "Red"
 	print -G $V "Green"
 	print -Y $V "Yellow"
 	print -B $V "Blue"
 	print -P $V "Purple"
 	print -C $V "Cyan"
 	print -W $V "White"
-	print -I -K $V "Bold Black" 
-	print -I -R $V "Bold Red" 
+	print -I -K $V "Bold Black"
+	print -I -R $V "Bold Red"
 	print -I -G $V "Bold Green"
 	print -I -Y $V "Bold Yellow"
 	print -I -B $V "Bold Blue"
